### ISSUE TITLE
dns配置部分疑似书写错误

### ISSUE THREAD

**Issue by XiaoLin05** [MetaCubeX/Meta-Docs#31]
既"geosite:geolocation-!cn":
      - "https://dns.cloudflare.com/dns-query#dns"
      - "https://dns.google/dns-query#dns"部分
在官方配置手册中，表明“书写规范应带引号，以防出现特殊字符”，而在手册中，表明引号为'，不是“”
可是在“快捷配置”中，既"geosite:geolocation-!cn":
      - "https://dns.cloudflare.com/dns-query#dns"
      - "https://dns.google/dns-query#dns"
引用的是“”，并不是'这个单引号，与官方配置手册“书写规范应带引号，以防出现特殊字符”产生冲突，需要检查该部分内容是否出现错误？

**Comment by xishang0128** [comment]
单引号双引号都能使用,都能避免识别成一些特使的定义
