### ISSUE TITLE
此页面有问题 https://wiki.metacubex.one/example/conf/ 

### ISSUE THREAD

**Issue by xyself** [MetaCubeX/Meta-Docs#47]
rules:
  - GEOIP,lan,直连,no-resolve 
 这一行并无拉取规则.
![image](https://github.com/user-attachments/assets/1342988a-435e-459b-9bb5-67cd52d99abe)

**Comment by xyself** [comment]
是因为保留地址的原因吗/文档中可以删除此行

**Comment by xishang0128** [comment]
geoip lan为内建规则,所以无数目

**Comment by xyself** [comment]
> geoip lan为应用内建规则，所以无数量

应该改为GEOIP,private
