### ISSUE TITLE
More information for smux protocols

### ISSUE THREAD

**Issue by APT-ZERO** [MetaCubeX/Meta-Docs#57]
Hello
currently docs says 'sing-mux, limited to protocols using tcp transmission'
there is no more info about different smux protocols
is smux, yamux, h2mux and tcp brutal effective on all protocol and transports? for example h2mux with padding for non-tls websocket
Thank you

**Comment by xishang0128** [comment]
![image](https://github.com/user-attachments/assets/beaa4ddf-d783-4fb4-9283-06a926c03652)


https://sing-box.sagernet.org/configuration/shared/multiplex/

Read upstream documents
